// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace App.Entity.Models
{
    public partial class Comments
    {
        public int CommentId { get; set; }
        public int? ArticleId { get; set; }
        public int? UserId { get; set; }
        public string Comment { get; set; }
        public DateTime? CommentDate { get; set; }
        public bool? Active { get; set; }

        public virtual Articles Article { get; set; }
        public virtual Users User { get; set; }
    }
}